version: 0.0.1.{build}
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
  - dotnet --version
  - dotnet restore src --verbosity m
build_script:
  - dotnet pack src -c Release
artifacts:
  - path: src/**/*.nupkg
    name: Nuget Packages
    type: NuGetPackage
clone_depth: 1
deploy: off
