version: 0.0.0-{build}+{commitId}
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
  - dotnet --version
  - dotnet restore src --verbosity m
build_script:
  - dotnet pack src -c Release
artifacts:
  - path: src/**/*.nupkg
    name: Nuget Packages
    type: NuGetPackage
clone_depth: 1
deploy:
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: eEi8gt5ne+a+N5fYINa2DqF7DCqOzYCE5udL5XzZm2qhcaMJkg9Tg4d0QObF9s3L
    skip_symbols: false
    artifact: /dist\/.*\.nupkg/